---
schema-version: '1.1'
build:
  name: OpenSearch
  version: 2.18.0
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-al2-opensearch-build-v1
    args: -e JAVA_HOME=/opt/java/openjdk-21
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: 2.x
  - name: performance-analyzer
    repository: https://github.com/gaiksaya/performance-analyzer.git
    ref: 2.x
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler